name: 'Build and publish npm package'
permissions:
  contents: read
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_publish:
    name: Build and publish npm package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 20.x

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run coverage

      - name: Build package
        run: npm run build

      - name: Publish package to npm
        id: publish
        uses: JS-DevTools/npm-publish@v4
        with:
           token: ${{ secrets.NPM_TOKEN_NEW }}

      - name: Update scope name in package json file for GitHub
        uses: restackio/update-json-values-action@v1.0.0
        with:
          file: package.json
          values: '{"@master-key-g/gulp-shell": "@master-key-g/gulp-shell"}'

      - name: Publish package to GitHub
        id: publishgithub
        uses: JS-DevTools/npm-publish@v2
        with:
          password: ${{secrets.test}}
          Username: ${{secrets.name}}
          registry: 'https://npm.pkg.github.com'

      - if: ${{ steps.publish.outputs.type }}
        run: |
          echo "Version changed!"
